### ISSUE TITLE
understanding the binding

### ISSUE THREAD

**Issue by benkoshy** [afcapel/stimulus-autocomplete#20]
Hi there

Thank you for your code. I have a question re: the following [lines](https://github.com/afcapel/stimulus-autocomplete/blob/c3a98a98961f25a24c0d7a06f3731bd86af90662/src/autocomplete.mjs#L15) (reproduced below):

```js
    // autocomplete.mjs
    this.onInputChange = debounce(this.onInputChange.bind(this), 300)
    this.onResultsClick = this.onResultsClick.bind(this)
    this.onResultsMouseDown = this.onResultsMouseDown.bind(this)
    this.onInputBlur = this.onInputBlur.bind(this)
    this.onKeydown = this.onKeydown.bind(this)
```

The onResultsClick methods etc. all refer to `this` within the method - which will refer to the current controller anyway, won't it? If that's the case then won't the above code be superfluous? Was seeking a pointer.

chrs

Ben

**Comment by drnic** [comment]
I'm learning too; but my understanding is that each `addEventListener` needs to be given a function that can be invoked *outside* the context of the controller object -- where `this` will have some other meaning.

So, we could refactor:

```
this.onKeydown = this.onKeydown.bind(this)
this.inputTarget.addEventListener("keydown", this.onKeydown)
```
into
```
this.inputTarget.addEventListener("keydown", this.onKeydown.bind(this))
```

But, during `disconnect` we invoke `removeEventListener("keydown", fn)` and we need to reference the same `fn`, which was `this.onKeydown.bind(this)`.

So we need to store `this.onKeydown.bind(this)` in an instance variable that `disconnect` can reference.

In `connect` it stores this `.bind(this)` version of the original function back as the same function name:

```
this.onKeydown = this.onKeydown.bind(this)
```

Again, this is so the `disconnect` function can use the same function handler for the `removeEventListener` call.

Since we've got a copy of `this.onKeydown` ready for `disconnect` we now use it for `connect` too so its the same handler:

```
this.inputTarget.addEventListener("keydown", this.onKeydown)
```

I think.

**Comment by benkoshy** [comment]
ok chrs @drnic appreciate the pointer.
